management:
    tracing:
      enabled: true 
      sampling:
        probability: 1.0 # 100% sampling for development 
    zipkin:
      tracing:
        endpoint: http://zipkin:9411/api/v2/spans 
    endpoints:
      web:
        exposure: 
          include: health,info,prometheus 
    endpoint:
      health:
        show-details: always  
