spring:
    application:
      name: product-service
server:
  port: 8383
  config: 
    import: vault://
  datasource: 
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
