spring:
    application:
      name: product-service
server:
  port: 8383
  # config: 
  #   import: vault://
  datasource: 
    username: ${spring.datasource.username:defaultUser}
    password: ${spring.datasource.password:defaultPassword}
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
